### ISSUE TITLE
path, username and password

### ISSUE THREAD

**Issue by cmsethi** [Abhijith14/Project-FTPServer#1]
hi, thanks for making this project.  Directory path is not working. username, password box not showing. I'm running the vs code. 
And how to disconnect the server?
chander mohan

**Comment by Abhijith14** [comment]
Hello chandra mohan. Sorry for the late reply.
1. Sometimes the ngrok versions might differ from the time of my deployment and from the time you are testing this.
But I just rechecked and I haven't seen any issues. It still works as expected. Though I think the problem might be that your URL can be wrong. 

<img width="846" alt="image" src="https://user-images.githubusercontent.com/53612189/204919678-422afc36-d1ef-40a7-99c3-66fa75c83eac.png">


ngrok global url sometimes wont work. So maybe try the http://localhost:1560 link. That should open the html page. Let me know if you face any issues.


2. Also, there is no button to disconnect the server. You can either stop your python code or close your ngrok terminal to shut down your connection.

**Comment by cmsethi** [comment]
hi Abhijith,
After going through all the files, now it has started working the way it should.But how could I add multiple directories in the PATH, like d:\\folder1. e:\\folder2?-even in HTTP server script not able to get that.I'm not a professional coder, but i enjoy learning to code
Could you please help me with that?

I'm an actor and also conduct workshops,- learning to code for me is some kind of... stress buster!! ...and I really enjoy it(of course) with the help of people like you.
looking forward to hearing from you,thanks, warm regards


chander mohan 

    On Thursday, 1 December, 2022 at 03:47:45 am IST, ABHIJITH UDAYAKUMAR ***@***.***> wrote:  
 
 


Hello chandra mohan. Sorry
   
   - Sometimes the ngrok versions might differ from the time of my deployment and from the time you are testing this.   
But I just rechecked and I haven't seen any issues. It still works as expected. Though I think the problem might be that your URL can be wrong.



ngrok global url sometimes wont work. So maybe try the http://localhost:1560 link. That should open the html page. Let me know if you face any issues.
   
   - Also, there is no button to disconnect the server. You can either stop your python code or close your ngrok terminal to shut down your connection.

**Comment by Abhijith14** [comment]
Hello chandra mohan, 
There are many ways where you can create a FTP server. The one that I did is a pretty basic version and was just to understand how it all connects. But if you want to create an advanced server with high security and authentication system for multiple drives/paths, you might have to check an alternate solution. There is a way in python, though I never have tried it myself but you might be able to get it right. If you check my code, I used os.chdir() function to set the current working directory to whatever path i specified. 

![image](https://user-images.githubusercontent.com/53612189/205056236-5695118f-43fc-403f-92fe-2fa649e737cb.png)

You might be able to get this path during run time. Maybe like in the html page, ask the user which path he/she wants and give them some options like d:\\folder1. e:\\folder2 and then based on their selected path, give them an authentication screen. This should help you get to your solution.

Thanks for the idea. I will work on this concept and let you know. Thank you for reaching back to me.
